# Generated by Django 5.0.3 on 2024-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.CharField(max_length=500, verbose_name='License URL'),
        ),
    ]
