# Generated by Django 5.0.3 on 2024-03-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_license_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='SPDX license identifier'),
        ),
    ]
