# Generated by Django 5.0.3 on 2024-03-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='URL slug')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('license', models.CharField(max_length=50, verbose_name='License shortcode')),
                ('license_url', models.CharField(max_length=50, verbose_name='License URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('photos', models.ManyToManyField(to='photos.photo', verbose_name='Photos')),
            ],
        ),
    ]
