# Generated by Django 5.0.3 on 2024-03-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('photos', '0002_photo_image_exif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='license_url',
        ),
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.AddField(
            model_name='album',
            name='location',
            field=models.CharField(blank=True, max_length=500, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug'),
        ),
        migrations.CreateModel(
            name='AlbumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='photos.album', verbose_name='Album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='photos.photo', verbose_name='Photo')),
            ],
        ),
    ]
