# Generated by Django 5.0.3 on 2024-03-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_license_identifier'),
        ('photos', '0003_remove_album_license_url_remove_album_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo', verbose_name='Hero image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.license', verbose_name='License'),
        ),
        migrations.CreateModel(
            name='AlbumList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('albums', models.ManyToManyField(to='photos.album', verbose_name='Albums')),
            ],
        ),
    ]
